const mongoose = require('mongoose')

const Jobschema = new mongoose.Schema({
    BookingSource: {
        type: String,
    },
    Carrier:{
        type:String
    } ,
    CarrierBookRef:{
        type:String
    } ,
    CarrierDoc:{
        type:String
    },
    CarrierDocDate:{
        type:String
    },
    CarrierDocs:{
        type:String,
    },
    ChargeWeight:{
        type:String
    },
    Commodity:{
        type:String
    },
    Container20ft:{
        type:String
    },
    Container40ft:{
        type:String
    },
    CostData:{
        type:[{
            CostBuyingRate:{
                type:String
            },
            CostCurrency:{
                type:String
            },
            CostExRate:{
                type:Number
            },
            CostFcGrossAmt:{
                type:Number
            },
            CostLcAmount:{
                type:Number
            },
            CostRemark:{
                type:String
            },
            Costparty:{
                type:String
            },
            CostpartyType:{
                type:String
            },
            Costrate:{
                type:String
            },
            NetLc:{
                type:Number
            },
            code:{
                type:String
            },
            description:{
                type:String
            },
            quantity:{
                type:String
            },
            tariffTerm:{
                type:String
            },
            uom:{
                type:String
            },
            uomType:{
                type:String
            }
        }]
    },
        Customer:{
            type:String
        },
        CustomerOU:{
            type:String
        },
        CustomerRef:{
            type:String
        },
        CustomerServicePerson:{
            type:String
        },
        CustomsDoc:{
            type:String
        },
        DangerousGoods:{
            type:String
        },
        Date:{
            type:String
        },
        DeliveryAgent:{
            type:String
        },
        DeliveryTerm:{
            type:String
        },
        Destination:{
            type:String
        },
        DischPort:{
            type:String
        },
        DocType:{
            type:String
        },
        FreightTerms:{
            type:String
        },
        HouseDoc:{
            type:String
        },
        HouseDocDate:{
            type:String
        },
        HsCode:{
            type:String
        },
        LoadPort:{
            type:String
        },
        LoadType:{
            type:String
        },
        NominationAgent:{
            type:String
        },
        NominationOU:{
            type:String
        },
        NumberOfPkgs:{
            type:String
        },
        OfficeLocation:{
            type:String
        },
        Origin:{
            type:String
        },
        OriginAgent:{
            type:String
        },
        PackageType:{
            type:String
        },
        PickupTerm:{
            type:String
        },
        RevenueData:{
            type:[{
                NetLc:{
                    type:Number
                },
                RevenueCurrency:{
                    type:String
                },
                RevenueExRate:{
                    type:Number
                },
                RevenueLcAmount:{
                    type:Number
                },
                RevenueRemark:{
                    type:String
                },
                Revenuparty:{
                    type:String
                },
                RevenupartyType:{
                    type:String
                },
                Revenurate:{
                    type:String
                },
                code:{
                    type:String
                },
                description:{
                    type:String
                },
                quantity:{
                    type:String
                },
                tariffTerm:{
                    type:String
                },
                uom:{
                    type:String
                },
                uomType:{
                    type:String
                }
            }]
        },
        SalesPerson:{
            type:String
        },
        SeaShipmentType:{
            type:String
        },
        Service:{
            type:String
        },
        TSLocallyDelivered:{
            type:String
        },
        Volume:{
            type:String
        },
        Voyage:{
            type:String
        },
        Weight:{
            type:String
        },
        consigneeAddress:{
        type:String
        },
        consigneeName:{
            type:String
        },
        eta:{
            type:String
        },
        etd:{
            type:String
        },
        notifyAddress:{
            type:String
        },
        notifyName:{
            type:String
        },
        shipperAddress:{
            type:String
        },
        shipperName:{
            type:String
        },
        tos:{
            type:String
        }
})
const Job = mongoose.model('Job',Jobschema);
module.exports = Job;